apiVersion: v1
kind: ReplicationController
metadata:
  name: static-web
  labels:
    role: myrole
    app: myapp
    type: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: static-web
      labels:
       role: myrole
    spec:
      containers:
        - name: web
          image: nginx
          ports:
           - name: web
             containerPort: 80
             protocol: TCP